name: BoardGame CICD

on:
  push:
    branches: ["master"]

jobs:
  build:

    runs-on: label-1

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'

    - name: Compile with Maven
      run: mvn compile 
      
    - name: Test with Maven
      run: mvn test 

    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master 
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}

    - name: Trivy FS Scan
      run: |
        trivy fs --format table -o trivy-fs-report.html .

    - name: Package with Maven
      run: mvn clean package

    - uses: actions/upload-artifact@v4
      with:
        name: Boardgame
        path: target/*.jar
