name: boardgame CICD

on:
  push:
    branches: ["master"]

jobs:
  build:
    name: Maven Compile Code
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'

    - name: Compile with Maven
      run: mvn compile 


  test:
    name: Maven Test Code
    runs-on: self-hosted

    steps:
      
    - name: Test with Maven
      run: mvn test 
